# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.16.2
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/hoshino/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/hoshino/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/hoshino/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/hoshino/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/hoshino/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/hoshino/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/hoshino/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/hoshino/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/hoshino/anacon

#### 3. Create a null vector of size 10 (★☆☆)

In [44]:
a = np.zeros((10))

#### 4.  How to find the memory size of any array (★☆☆)

In [46]:
a.nbytes

80

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [13]:
a = np.arange(10, 50)
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [15]:
np.nonzero([1, 2, 0, 0, 4, 0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [17]:
np.random.random((3,3,3))

array([[[0.90766081, 0.35484346, 0.14137324],
        [0.83030622, 0.08447738, 0.25603362],
        [0.43298798, 0.9759991 , 0.99544022]],

       [[0.89190357, 0.29296657, 0.99883082],
        [0.59621613, 0.38237504, 0.36561704],
        [0.92686809, 0.80549723, 0.15132144]],

       [[0.08529172, 0.92265129, 0.91773971],
        [0.3308363 , 0.65204008, 0.25940636],
        [0.07521543, 0.46122283, 0.79132548]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [22]:
a = np.random.random((10, 10))
print(np.max(a))
print(np.min(a))

0.9929558396429009
0.007995122448371528


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [24]:
np.random.random((1000)).mean()

0.4949149156104008

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [32]:
np.pad(np.zeros((3,4)), mode="constant", pad_width=1, constant_values=1)

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [33]:
np.pad(a, mode="constant", pad_width=1, constant_values=0)

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.90080976, 0.94121107, 0.7871577 , 0.72147987,
        0.35600332, 0.45415371, 0.88919518, 0.32718748, 0.72638756,
        0.63063871, 0.        ],
       [0.        , 0.1675302 , 0.68619989, 0.76232591, 0.14107855,
        0.60818463, 0.56213764, 0.161019  , 0.274114  , 0.73345183,
        0.55896543, 0.        ],
       [0.        , 0.41740224, 0.6832808 , 0.57746983, 0.13655579,
        0.14547839, 0.31826981, 0.37756289, 0.04650993, 0.36379807,
        0.00799512, 0.        ],
       [0.        , 0.01625183, 0.11102453, 0.3314276 , 0.59465487,
        0.34067014, 0.54704032, 0.32809002, 0.94146071, 0.47501801,
        0.02379195, 0.        ],
       [0.        , 0.66896405, 0.47398687, 0.09873448, 0.33526194,
        0.33073024, 0.25438617, 0.27042837, 0.83610687, 0.10781057,
        0.33230048,

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [39]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [42]:
np.diagflat(range(1,5), -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [53]:
array = np.array([
    [11, 22, 33],
    [77, 88, 99],
    [44, 55, 66]]
)
np.argmax(array)

5

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [55]:
np.tile([[0, 1], [1, 0]], (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [59]:
a = np.random.random((5, 5))
a /= np.sum(a ** 2)
a

array([[0.07620468, 0.0591964 , 0.07592051, 0.06303346, 0.02982357],
       [0.10566334, 0.09958348, 0.10709474, 0.06751977, 0.01435305],
       [0.02923949, 0.09457847, 0.01744194, 0.08531968, 0.10069095],
       [0.07372765, 0.08234868, 0.06140683, 0.05882801, 0.09479609],
       [0.0907272 , 0.01660859, 0.01918913, 0.03360393, 0.01377151]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [60]:
dt = np.dtype(np.uint32)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [64]:
a = np.arange(15).reshape((5, 3))
b = np.arange(6).reshape((3, 2))
np.matmul(a, b)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [67]:
a = np.arange(15)
a[np.logical_and(a>3,a<8)] = 0
a

array([ 0,  1,  2,  3,  0,  0,  0,  0,  8,  9, 10, 11, 12, 13, 14])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [69]:
from numpy import *
print(sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [79]:
Z = np.arange(3)
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [82]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
a = np.arange(15)
b = np.arange(3, 20)
np.intersect1d(a, b)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [84]:
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [85]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [88]:
np.datetime64("today", "D") + np.timedelta64(1, "D")

numpy.datetime64('2019-08-12')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [91]:
np.arange("2016-06", "2016-07", dtype="datetime64[D]")

array(['2016-06-01', '2016-06-02', '2016-06-03', '2016-06-04',
       '2016-06-05', '2016-06-06', '2016-06-07', '2016-06-08',
       '2016-06-09', '2016-06-10', '2016-06-11', '2016-06-12',
       '2016-06-13', '2016-06-14', '2016-06-15', '2016-06-16',
       '2016-06-17', '2016-06-18', '2016-06-19', '2016-06-20',
       '2016-06-21', '2016-06-22', '2016-06-23', '2016-06-24',
       '2016-06-25', '2016-06-26', '2016-06-27', '2016-06-28',
       '2016-06-29', '2016-06-30'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [92]:
a = np.arange(3)
b = np.arange(3, 6)
(a.__iadd__(b))*(-a/2)

array([ -4.5, -12.5, -24.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [93]:
np.tile(np.arange(5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [94]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [95]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [99]:
a = np.sort(np.random.random(10))
a

array([0.06968049, 0.12384725, 0.26266584, 0.28512976, 0.30050902,
       0.37348813, 0.45896355, 0.47619864, 0.71760393, 0.83588714])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [106]:
a = np.arange(10).reshape((2, 5))
%timeit np.sum(a)
def sumt(a):
    t = 0
    for i in a:
        t += i
%timeit sumt(a)
    

2.94 µs ± 51.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.93 µs ± 99.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [108]:
a = np.random.random(4)
b = a 
c = np.random.random(4)
np.array_equal(a, c)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [112]:
a.flags["WRITEABLE"] = False
a
a[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [114]:
Z = np.random.random((10, 2))
r = np.sqrt(np.sum(Z ** 2, -1))
theta = np.arctan(Z[:, -1]/Z[:, 0])
theta

array([1.14344037, 0.69167293, 0.74464648, 0.54430116, 1.10474407,
       0.28270386, 0.81218885, 0.32950272, 0.26844122, 0.73183009])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [115]:
Z = np.random.random(10)
print(Z)
idx = np.unravel_index(np.argmax(Z), Z.shape)
Z[idx] = 0
print(Z)

[0.91327621 0.44819014 0.90751922 0.14680165 0.85062559 0.39022343
 0.61739459 0.7236832  0.37179418 0.65201644]
[0.         0.44819014 0.90751922 0.14680165 0.85062559 0.39022343
 0.61739459 0.7236832  0.37179418 0.65201644]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [121]:
dt = np.dtype([("x", "<f4"), ("y", "<f4")])
Z = np.array([(0, 0), (0, 1)], dtype=dt)
Z["x"]

array([0., 0.], dtype=float32)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [124]:
X = np.random.rand(4)
Y = np.random.rand(3)
C = 1. / X[:, None] - Y
C

array([[1.23170212, 1.78819168, 1.67643494],
       [0.23961967, 0.79610923, 0.68435249],
       [0.12708398, 0.68357355, 0.57181681],
       [1.10113971, 1.65762927, 1.54587254]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [134]:
print(np.iinfo(np.int8))
print(np.iinfo(np.int16))
print(np.iinfo(np.int32))
print(np.iinfo(np.int64))

print(np.iinfo(np.uint8))
print(np.iinfo(np.uint16))
print(np.iinfo(np.uint32))
print(np.iinfo(np.uint64))

print(np.finfo(np.float32))
print(np.finfo(np.float64))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for uint8
---------------------------------------------------------------
min = 0
max = 255
---------------------------------------------------------------

Machine parameters for uint16
-----------------------------

#### 49. How to print all the values of an array? (★★☆)

In [140]:
#np.set_printoptions(threshold=np.inf)
Z = np.random.random(1000)
print(Z)

[1.39798776e-01 6.69724983e-01 5.87358700e-01 2.66794860e-01
 6.04634358e-02 3.75329453e-01 6.70318075e-01 7.76229210e-02
 1.83058870e-01 8.73172322e-01 1.80373374e-01 4.23921159e-01
 9.43834689e-01 7.77251243e-01 5.00110242e-01 4.48791174e-01
 3.13091233e-02 1.61199559e-01 4.40544415e-01 4.87060138e-01
 4.50351242e-01 3.21611617e-01 4.95937922e-01 3.49077017e-02
 5.67107275e-01 5.36396414e-01 7.27594881e-01 9.17879516e-01
 9.63430025e-01 7.26479698e-01 6.62872258e-01 5.36090160e-01
 9.34553190e-01 6.72610348e-01 8.79814278e-01 9.61289553e-01
 2.10129772e-02 3.85393048e-01 9.34358600e-01 3.06922477e-01
 6.72947154e-02 6.42373908e-02 1.84203502e-01 5.08936306e-01
 8.82285170e-02 5.74399909e-01 5.58803426e-01 1.14857617e-01
 6.52764230e-01 6.04308189e-01 9.67814801e-02 4.32253793e-01
 8.13910272e-01 3.69212546e-02 9.19624325e-01 2.07435193e-01
 5.01711878e-01 8.49120969e-01 7.22187441e-01 7.41335990e-01
 7.27409269e-01 8.63633553e-01 5.73524304e-01 5.31048337e-01
 5.98397422e-01 6.717663

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [145]:
Z = np.random.random((100, 100))
v = 0.61
delta = np.unravel_index(np.argmin(np.abs(Z - v)), Z.shape)
Z[delta]

0.6099906106406638

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [136]:
dt_p = np.dtype([("x", "<f4"), ("y", "<f4")])
dt_c = np.dtype([("r", "u1"), ("g", "u1"), ("b", "u1")])
dt = np.dtype([("position", dt_p), ("color", dt_c)])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [148]:
Z = np.random.random((10, 10))
Z -= np.mean(Z, -1)
Z

array([[-0.36161723, -0.10178186,  0.36603334,  0.48375509, -0.22403909,
         0.21073356, -0.17537835,  0.14951557,  0.12113868,  0.20607069],
       [ 0.04302455, -0.09321373, -0.5681908 ,  0.21652102, -0.1285788 ,
         0.23538868,  0.08302808,  0.01250702, -0.12000777,  0.40206644],
       [ 0.04254638,  0.27358306, -0.4883024 ,  0.04563193,  0.03878744,
        -0.04862411,  0.22689358,  0.42233565,  0.34333062,  0.42641462],
       [-0.17880203, -0.45226342, -0.60137844,  0.51979739,  0.34545309,
         0.30480851, -0.40646855, -0.31142838,  0.34871235, -0.35410619],
       [-0.26804078,  0.0957622 , -0.0269478 , -0.06917759, -0.22905402,
        -0.46086139,  0.10291264,  0.2590359 , -0.37506931, -0.12655484],
       [-0.26423259,  0.11107983,  0.02024041,  0.02218282,  0.54959875,
         0.26302043, -0.21103711,  0.13083437, -0.40831477,  0.02022182],
       [-0.48457505, -0.02904235,  0.02921562, -0.23507066, -0.37180422,
         0.32847173,  0.32315798, -0.21432824

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [150]:
Z = np.random.random((10, 10))
np.any(np.all(Z, axis = 0) == 0)

False

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [155]:
Z = np.random.random((4,3,2,5))
np.add.reduce(Z, axis=(-2, -1)).shape

(4, 3)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [156]:
Z = np.random.random(300)
i = np.arange(3, 39)
np.mean(Z[i])

0.49863044412230617

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)